# Generated by Django 2.1.5 on 2019-01-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20190127_1831'),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('target_amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashProjectTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='charity.CashProject')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='volunteer.Volunteer')),
            ],
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name_plural': 'charities'},
        ),
        migrations.AddField(
            model_name='cashproject',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_projects', to='charity.Charity'),
        ),
        migrations.AddField(
            model_name='cashproject',
            name='volunteers',
            field=models.ManyToManyField(through='charity.CashProjectTransaction', to='volunteer.Volunteer'),
        ),
    ]
