# Generated by Django 2.1.5 on 2019-01-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20190127_1905'),
        ('charity', '0002_auto_20190127_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCashProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('need_male', models.BooleanField(db_index=True)),
                ('need_female', models.BooleanField(db_index=True)),
                ('min_age', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('abilities', models.ManyToManyField(related_name='projects', to='volunteer.Ability')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_cash_projects', to='charity.Charity')),
                ('volunteers', models.ManyToManyField(related_name='non_cash_projects', to='volunteer.Volunteer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonCashProjectTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(5, 'Saturday'), (6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], db_index=True)),
                ('time', models.IntegerField(choices=[(0, 'Morning'), (1, 'Noon'), (2, 'Afternoon'), (3, 'Night')], db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='charity.NonCashProject')),
            ],
        ),
        migrations.AlterField(
            model_name='cashproject',
            name='volunteers',
            field=models.ManyToManyField(related_name='cash_projects', through='charity.CashProjectTransaction', to='volunteer.Volunteer'),
        ),
        migrations.AlterUniqueTogether(
            name='noncashprojecttimeslot',
            unique_together={('project', 'weekday', 'time')},
        ),
    ]
