# Generated by Django 2.1.5 on 2019-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20190127_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashproject',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='cash_projects', through='charity.CashProjectTransaction', to='volunteer.Volunteer'),
        ),
        migrations.AlterField(
            model_name='noncashproject',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='projects', to='volunteer.Ability'),
        ),
        migrations.AlterField(
            model_name='noncashproject',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='non_cash_projects', to='volunteer.Volunteer'),
        ),
    ]
