# Generated by Django 2.1.5 on 2019-01-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_auto_20190128_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashproject',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noncashproject',
            name='description',
            field=models.TextField(),
        ),
    ]
