# Generated by Django 2.1.5 on 2019-01-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20190127_1909'),
        ('charity', '0006_auto_20190128_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCashProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(0, 'CHARITY'), (1, 'VOLUNTEER')])),
                ('message', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (-1, 'REJECTED'), (1, 'ACCEPTED')], db_index=True, default=0)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='charity.Charity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='charity.NonCashProject')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='volunteer.Volunteer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='noncashprojectrequest',
            unique_together={('project', 'volunteer', 'charity')},
        ),
    ]
