# Generated by Django 2.1.5 on 2019-01-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20190127_1909'),
        ('charity', '0007_auto_20190128_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(0, 'CHARITY'), (1, 'VOLUNTEER')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='charity.Charity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='volunteer.Volunteer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('target', 'volunteer', 'charity')},
        ),
    ]
