# Generated by Django 2.1.5 on 2019-02-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_auto_20190129_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashproject',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='cashprojecttransaction',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='noncashproject',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='noncashprojectrequest',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='noncashprojecttimeslot',
            options={'ordering': ('-id',)},
        ),
    ]
