# Generated by Django 2.1.5 on 2019-01-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], db_index=True, max_length=1, null=True)),
                ('age', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('abilities', models.ManyToManyField(related_name='users', to='volunteer.Ability')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], db_index=True)),
                ('time', models.IntegerField(choices=[(0, 'Morning'), (1, 'Noon'), (2, 'Afternoon'), (3, 'Night')], db_index=True)),
                ('is_available', models.BooleanField(db_index=True, default=False)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='volunteer.Volunteer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='volunteertimeslot',
            unique_together={('volunteer', 'weekday', 'time')},
        ),
    ]
