# Generated by Django 2.1.5 on 2019-01-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'abilities'},
        ),
    ]
