# Generated by Django 2.1.5 on 2019-01-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20190127_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteertimeslot',
            name='weekday',
            field=models.IntegerField(choices=[(5, 'Saturday'), (6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], db_index=True),
        ),
    ]
