# Generated by Django 2.1.5 on 2019-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20190127_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='users', to='volunteer.Ability'),
        ),
    ]
