# Generated by Django 2.1.5 on 2019-01-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20190127_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(db_index=True, default='hoda', max_length=50),
            preserve_default=False,
        ),
    ]
