# Generated by Django 2.1.5 on 2019-02-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_volunteer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ('-id',), 'verbose_name_plural': 'abilities'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='volunteertimeslot',
            options={'ordering': ('-id',)},
        ),
    ]
